"""add_status_erreur_to_recherches_financement

Revision ID: 231885893c5f
Revises: 3bb0d08852d4
Create Date: 2026-08-19 18:05:30.839116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231885893c5f'
down_revision: Union[str, None] = '3bb0d08852d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted : server_default requis pour
    # backfiller les lignes existantes (créées avant ce champ, donc déjà terminées) ###
    with op.batch_alter_table('recherches_financement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False, server_default='termine'))
        batch_op.add_column(sa.Column('erreur', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recherches_financement', schema=None) as batch_op:
        batch_op.drop_column('erreur')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
