"""add_recherches_financement

Revision ID: 3bb0d08852d4
Revises: 771d4ae5e488
Create Date: 2026-08-19 07:50:33.065060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb0d08852d4'
down_revision: Union[str, None] = '771d4ae5e488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recherches_financement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('criteres', sa.Text(), nullable=False),
    sa.Column('resultats', sa.Text(), nullable=False),
    sa.Column('recherche_live', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recherches_financement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recherches_financement_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recherches_financement_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recherches_financement_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recherches_financement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recherches_financement_user_id'))
        batch_op.drop_index(batch_op.f('ix_recherches_financement_project_id'))
        batch_op.drop_index(batch_op.f('ix_recherches_financement_id'))

    op.drop_table('recherches_financement')
    # ### end Alembic commands ###
