"""add_generation_jobs

Revision ID: 5ef2b1321793
Revises: 231885893c5f
Create Date: 2026-08-19 18:57:52.878374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef2b1321793'
down_revision: Union[str, None] = '231885893c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_id'))

    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
